#define BOOL unsigned char
#define OCTET unsigned char
#define ULONG unsigned long
#define SPR 0
#define PCX 1
#define MASK_ON 1
#define MASK_OFF 0
#define FAUX 0
#define VRAI 1
#define LIBRE 0
#define OCCUPE 1
#define PAGE0 0
#define PAGE1 1
#define LG_BOB 7
#define HT_BOB 11
#define LIMITE_X_ECRAN 320
#define LIMITE_Y_ECRAN 400
#define OFF 0
#define ON 1
#define CURS_FOND_FLECHE 0
#define CURS_FLECHE_1 1
#define CURS_FLECHE_2 2
#define CURS_FLECHE_3 3
#define CURS_FLECHE_4 4
#define CURS_LONG_FLECHE 13
#define CURS_HAUT_FLECHE 14
#define CURS_FOND_CROIX 5
#define CURS_CROIX 6
#define CURS_LONG_CROIX 7
#define CURS_HAUT_CROIX 11
#define BOB_BLOC_NOIR 7
#define BOB_BLOC_BLEU 8
#define BOB_BLOC_GRIS 9
#define NB_BOB_BLOC 3
#define BLOC_LONG 10
#define BLOC_HAUT 10
#define CHIF_LONG 5
#define CHIF_LARG 7
#define BOB_CHIFFRE 10
#define CHIF_0 10
#define CHIF_1 11
#define CHIF_2 12
#define CHIF_3 13
#define CHIF_4 14
#define CHIF_5 15
#define CHIF_6 16
#define CHIF_7 17
#define CHIF_8 18
#define CHIF_9 19
#define BOB_PASTILLE 20
#define NB_BOB_PASTILLE 38
#define PASTILLE_LONG 7
#define PASTILLE_HAUT 11
#define BORDURE 20
#define DESSIN 21
#define PORTE_BLANCHE_MOBILE 22
#define PORTE_ROUGE_FERMEE 23
#define PORTE_VERTE_FERMEE 24
#define PORTE_BLEU_FERMEE 25
#define PORTE_ROUGE_OUVERTE 26
#define PORTE_VERTE_OUVERTE 27
#define PORTE_BLEU_OUVERTE 28
#define CLE_ROUGE 29
#define CLE_VERTE 30
#define CLE_BLEU 31
#define BOULE_BLEU 32
#define DIAMANT 33
#define BOULE_VERTE 34
#define BOULE_ROUGE 35
#define ETOILE_VIE 36
#define ETOILE_MORT 37
#define SERPENT_SOUPLE 38
#define SERPENT_RAIDE 39
#define TEMPS_PLUS 40
#define TEMPS_MOINS 41
#define IMMORTALITE 42
#define MORTALITE 43
#define AVANCE_LENTE 44
#define AVANCE_RAPIDE 45
#define VITESSE_RAPIDE 46
#define VITESSE_MOYENNE 47
#define VITESSE_LENTE 48
#define STOP_SERPENT_ROUGE 49
#define STOP_SERPENT_VERT 50
#define STOP_SERPENT_BLEU 51
#define SENS_SERPENT_ROUGE 52
#define SENS_SERPENT_VERT 53
#define SENS_SERPENT_BLEU 54
#define VITESSE_SERPENT_ROUGE 55
#define VITESSE_SERPENT_VERT 56
#define VITESSE_SERPENT_BLEU 57
#define FOND_1 58
#define FOND_2 59
#define BOB_SERPENTS 60
#define NB_BOB_SERPENT_COULEUR 9
#define SERPENT_LONG 7
#define SERPENT_HAUT 11
#define SERPENT_ROUGE 60
#define SERPENT_VERT 69
#define SERPENT_BLEU 78
#define SERPENT_BLANC 87
#define BOB_BORDURE 96
#define NB_BOB_BORDURE 16
#define BORDURE_LONG 7
#define BORDURE_HAUT 11
#define BOB_FOND 112
#define NB_BOB_FOND 1
#define FOND_LONG 7
#define FOND_HAUT 11
#define BOB_SNAKLES 113
#define NB_BOB_SNAKLES 10
#define SNAKLES_LONG 7
#define SNAKLES_HAUT 11
#define SNAKLES_ROUGE 113
#define SNAKLES_VERT 123
#define SNAKLES_BLEU 133
#define SNAKLES_ORANGE 143
#define SNAKLES_BLANC 153
#define BOB_CHIFFRE_2 164
#define CHIF2_LONG 8
#define CHIF2_LARG 7
#define CHIF2_0 164
#define CHIF2_1 165
#define CHIF2_2 166
#define CHIF2_3 167
#define CHIF2_4 168
#define CHIF2_5 169
#define CHIF2_6 170
#define CHIF2_7 171
#define CHIF2_8 172
#define CHIF2_9 173
#define BOB_AUTRE 174
OCTET Lire_Page (void);
void Activer_Ecran (void);
void Desactiver_Ecran (void);
void Afficher_Page (OCTET);
void Afficher_Point (OCTET,short,short,OCTET);
OCTET Lire_Point (OCTET,short,short);
void Tracer_Droite (OCTET,short,short,short,short,OCTET);
void Cls (OCTET,OCTET);
void Lire_Palette (char*);
BOOL Lire_Image_Pcx (char*,OCTET,short,short,OCTET,
                     short,short,short,short);
BOOL Creer_Bob (short,short,short);
BOOL Lire_Bob (short,OCTET,short,short);
BOOL Afficher_Bob (OCTET,short,short,short,OCTET);
BOOL Detruire_Bob (short);
void Afficher_Nombre (OCTET,OCTET,OCTET,ULONG,short,short,OCTET);
void Definir_Bobs (void);
void Supprimer_Bobs (void);
