#define BOOL unsigned char
#define OCTET unsigned char
#define ULONG unsigned long
#define SPR 0
#define PCX 1
#define MASK_ON 1
#define MASK_OFF 0
#define FAUX 0
#define VRAI 1
#define LIBRE 0
#define OCCUPE 1
#define PAGE0 0
#define PAGE1 1
#define LG_BOB 7
#define HT_BOB 11
#define LIMITE_X_ECRAN 320
#define LIMITE_Y_ECRAN 400
#define OFF 0
#define ON 1
#define BOB_BLOC 0
#define NB_BOB_BLOC 2
#define BLOC_LONG 10
#define BLOC_HAUT 10
#define BOB_CHIFFRE2 10
#define NB_BOB_CHIFFRE2 10
#define CHIF2_LONG 8
#define CHIF2_HAUT 8
#define BOB_PASTILLE 20
#define NB_BOB_PASTILLE 38
#define PASTILLE_LONG 7
#define PASTILLE_HAUT 11
#define BOB_FOND 58
#define NB_BOB_FOND 1
#define FOND_LONG 7
#define FOND_HAUT 11
#define BOB_BORDURE 59
#define NB_BOB_BORDURE 16
#define BORDURE_LONG 7
#define BORDURE_HAUT 11
#define BOB_SERPENT_ROUGE 75
#define NB_BOB_SERPENT_ROUGE 24
#define SERPENT_ROUGE_LONG 7
#define SERPENT_ROUGE_HAUT 11
#define BOB_SERPENT_VERT 99
#define NB_BOB_SERPENT_VERT 24
#define SERPENT_VERT_LONG 7
#define SERPENT_VERT_HAUT 11
#define BOB_SERPENT_BLEU 123
#define NB_BOB_SERPENT_BLEU 24
#define SERPENT_BLEU_LONG 7
#define SERPENT_BLEU_HAUT 11
#define BOB_SERPENT_NOIR 147
#define NB_BOB_SERPENT_NOIR 24
#define SERPENT_NOIR_LONG 7
#define SERPENT_NOIR_HAUT 11
#define BOB_SERPENT_BLANC 171
#define NB_BOB_SERPENT_BLANC 24
#define SERPENT_BLANC_LONG 7
#define SERPENT_BLANC_HAUT 11
#define BOB_AUTRE 195
OCTET Lire_Page (void);
void Activer_Ecran (void);
void Desactiver_Ecran (void);
void Afficher_Page (OCTET);
void Afficher_Point (OCTET,short,short,OCTET);
OCTET Lire_Point (OCTET,short,short);
void Tracer_Droite (OCTET,short,short,short,short,OCTET);
void Effacer_Ecran (OCTET,OCTET);
void Cls (OCTET);
void Lire_Palette (char*);
BOOL Lire_Image_Pcx (char*,OCTET,short,short,OCTET,
                     short,short,short,short);
BOOL Creer_Bob (short,short,short);
BOOL Lire_Bob (short,OCTET,short,short);
BOOL Afficher_Bob (OCTET,short,short,short,OCTET);
BOOL Detruire_Bob (short);
void Afficher_Nombre (OCTET,OCTET,OCTET,ULONG,short,short,OCTET);
void Definir_Bobs (void);
void Supprimer_Bobs (void);
void Wait_Retrace (void);
